package demo10.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2016-03-06T13:25:19.491+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://impl.service.demo10/", name = "SayHi")
@XmlSeeAlso({ObjectFactory.class})
public interface SayHi {

    @WebMethod
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://impl.service.demo10/", className = "demo10.client.SayHi_Type")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://impl.service.demo10/", className = "demo10.client.SayHiResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
