package demo12.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2016-03-06T20:30:50.822+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://service.demo12/", name = "PersonService")
@XmlSeeAlso({})
public interface PersonService {

    @WebMethod
    @RequestWrapper(localName = "findPersonById", targetNamespace = "http://service.demo12/", className = "demo12.client.FindPersonById")
    @ResponseWrapper(localName = "findPersonByIdResponse", targetNamespace = "http://service.demo12/", className = "demo12.client.FindPersonByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public demo12.client.Person findPersonById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
